package it.polimi.vovarini.model.godcards;

import it.polimi.vovarini.model.Point;

import java.util.ArrayList;

/**
 * @class Behavior represents a general behavior influenced by card effects. It should represent a general rule-conditioned aspect of the game
 * @author Mattia Valassi
 */
public abstract class Behavior {

    /**
     * This method applies any bonus or malus generated by the effect of a previous card owned by a player that played before the current one
     * @param malusCard is the previous card whose effect is applied by the method
     * @return List of points that are blocked, meaning that the malus effect previously applied makes them illegal to reach or build.
     * If the effect is applied to an aspect not involving a Move, the list will be empty.
     * @author Mattia Valassi
     */


}
